### PR TITLE
Update Readme.md

### PR DESCRIPTION
**Pull request by mburati**
@jlidaka - Please review/update/pull-when-ready the suggested instructions update as discussed with @jbooth1

### CODE REVIEW

**Comment by jlidaka** [comment]
Mike, are you sure your wiki syntax is correct?  the replacement properties you have with <...> will cause issues if not formatted properly.  I think you might need some quotes like this:

`<some replacement stuff>`

**Comment by jlidaka** [comment]
I mixed up pull requests... I think the quotes are for the other....

**Comment by jlidaka** [comment]
Changes look good to me, if @jbooth1 agrees then we can close on the pull.

**Comment by jbooth1** [comment]
looks good to me @jlidaka

**Pull request merged**
